[colors.primary]
background = "#141118" # base00
foreground = "#a095b2" # base05

[colors.cursor]
text = "#141118"
cursor = "#a095b2"

[colors.selection]
background = "#27222f" # base02
text = "#f4f3f6"       # base07

[colors.normal]
black   = "#141118" # base00
red     = "#d4b0c7" # base08
green   = "#aed4b9" # base0B
yellow  = "#e2ccd0" # base0A
blue    = "#98a4ff" # base0D
magenta = "#d3a0e6" # base0E
cyan    = "#b4a0d4" # base0C
white   = "#a095b2" # base05

[colors.bright]
black   = "#3b3447" # base03
red     = "#d4b0c7" # base08
green   = "#aed4b9" # base0B
yellow  = "#e2ccd0" # base0A
blue    = "#98a4ff" # base0D
magenta = "#d3a0e6" # base0E
cyan    = "#b4a0d4" # base0C
white   = "#f4f3f6" # base07

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Never"

[env]
TERM = "xterm-256color"

[font]
size = 10
normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }
bold = { family = "JetBrains Mono Nerd Font", style = "Bold" }
italic = { family = "JetBrains Mono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrains Mono Nerd Font", style = "Bold Italic" }
# [font.normal]
# family = "JetBrains Mono Nerd Font"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
# auto_scroll = true
history = 2000

[window.dimensions]
columns = 120
lines = 40

[window]
dynamic_padding = true
padding = { x = 20, y = 10 }
decorations = "none"

