[MyTheme]
# Acentos
accent             = a095b2   # base05: texto principal / destaque leve
accent-active      = 98a4ff   # base0D: accent principal (botões, hover)
accent-inactive    = 4f455f   # base04: texto secundário / ícones inativos

# Banner / topo
banner             = 141118   # base00: fundo bem escuro
header             = 141118   # base00: topo de seção ou headers

# Bordas
border-active      = d3a0e6   # base0E: borda ativa / destaque neon
border-inactive    = 27222f   # base02: borda inativa escura

# Fundo / áreas principais
main               = 141118   # base01: superfícies elevadas / cards
highlight          = b4a0d4   # base0C: strings, destaques
subtext            = cac4d4   # base06: textos menores / labels
text               = a095b2   # base05: texto normal

# Notificações
notification       = d7bdef   # base0F: alertas leves
notification-error = f80000   # vermelho para erros
